### ISSUE TITLE
sklearn版本有点问题呀

### ISSUE THREAD

**Issue by HugoWang232608** [linlei1214/SITS-Former#1]
- scikit-learn==1.0.1 -> python[version='>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python==3.6.10

sklearn安装时出现问题，sklearn=1.0.1的适配的python版本至少应该是3.7，3.6.10不能使用，请问是不是写错了呢

**Comment by linlei1214** [comment]
您好，
是python=3.8，确实写错了，提交的比较马虎，感谢您提出错误。


林蕾
2022-2-23
在2022年2月22日 ***@***.***> 写道：

scikit-learn==1.0.1 -> python[version='>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python==3.6.10

sklearn安装时出现问题，sklearn=1.0.1的适配的python版本至少应该是3.7，3.6.10不能使用，请问是不是写错了呢

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by linlei1214** [comment]
> * scikit-learn==1.0.1 -> python[version='>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
> 
> Your python: python==3.6.10
> 
> sklearn安装时出现问题，sklearn=1.0.1的适配的python版本至少应该是3.7，3.6.10不能使用，请问是不是写错了呢
